### PR TITLE
idk typos or somethin

### PR DESCRIPTION
**Pull request by norbcodes**
I poke my nose in everything don't I?

### CODE REVIEW

**Comment by mf366-dev** [comment]
Yes you do, but im glad you did

**Comment by mf366-dev** [comment]
Yes you do, but im glad you did

**Comment by mf366-dev** [comment]
Yes you do, but im glad you did

**Comment by mf366-dev** [comment]
Yes you do, but im glad you did

**Comment by mf366-dev** [comment]
What happened? I see my comment 4 times?!

**Comment by norbcodes** [comment]
Github is on LSD XDDDDD

**Review by mf366-dev — APPROVED** [review]
Need to check for problems with Git, but yeah this is approved.

**Pull request merged**
